### ISSUE TITLE
change starting location map is centred on

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#101]
right now the map opens on Africa. We expect most of our initial users to be Europe and America. 

The scale is fine, just set opening location slightly higher up

**Comment by Islandersfan2016** [comment]
I'll try to fix this problem.

**Comment by Islandersfan2016** [comment]
I'm having trouble resolving this issue. Does anyone have suggestions? Should we make the map a little smaller in order to center Europe/US when it opens?

**Comment by AndyatFocallocal** [comment]
@Islandersfan2016 i dont see any issue with starting on this map zoom setting, so long as it zooms into a decent country sized level when 1st clicking a dot, and still zooms in to a large city sized level on the second click

![image](https://cloud.githubusercontent.com/assets/16229696/23132808/b844a0b0-f786-11e6-801f-546ca7769218.png)

**Comment by ydaniel98** [comment]
@Islandersfan2016 You can use the settings found in the Template.map.helper function. There you can set the centre of the map when it first loads.
