### ISSUE TITLE
Fix the React and CSS issues in these pages

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#1016]
the page here doesn't display correctly: https://focallocal.org/whitepaper/why

Half of the text inserts aren't appearing, and the CSS is a mess, mostly on mobile

Related files in Github:

https://github.com/focallocal/fl-maps/blob/master/imports/client/ui/pages/WhitePaper/Why/Content.js

https://github.com/focallocal/fl-maps/edit/master/imports/both/i18n/en/whitepaper/why.json

**Comment by vutran6853** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the React and CSS issues in these pages](https://trello.com/c/LXINJ3g0/697-fix-the-react-and-css-issues-in-these-pages)
