### ISSUE TITLE
Saw a post about this project on reddit...

### ISSUE THREAD

**Issue by ludanin** [focallocal/fl-maps#1100]
Hey I remember seeing a reddit post about this project over a week ago, apparently you needed a react Dev to help with the home page.

I'm a totally newb at reddit so I can't find the post again haha, this last weekend was super hectic and I knew I wouldn't be able to help, however, I'll have some free time tomorrow and probably more over the next weekend, so I'd like to know if you guys still need any help with the homepage? I know reddit has support for DMs so if you want to reach me over there my nickname is the same as the one I use in GitHub (@ludanin)

Also sorry if I shouldn't be opening issues about this, I just didn't know what's the best way to reach you, hope you're all doing great, cheers!

**Comment by AndyatFocallocal** [comment]
Hi @ludanin thanks for finding us here, i'd love to have you join in. 

We've got two React based tasks remaining before launch. 

Here's the 1st: https://publichappinessmovement.com/t/topic/2348/16

and here's the 2nd: https://publichappinessmovement.com/t/topic/2600

Kento has begun the homepage, although you are very welcome to chat to them and offer to build it together. Or you could take on the 2nd task solo. I'll add you to our Git, and the main place we communicate is on the platform the links above point to. There's a getting started guide in the Reactjs section. 

Welcome :)

**Comment by ludanin** [comment]
> Hi @ludanin thanks for finding us here, i'd love to have you join in.
> 
> We've got two React based tasks remaining before launch.
> 
> Here's the 1st: https://publichappinessmovement.com/t/topic/2348/16
> 
> and here's the 2nd: https://publichappinessmovement.com/t/topic/2600
> 
> Kento has begun the homepage, although you are very welcome to chat to them and offer to build it together. Or you could take on the 2nd task solo. I'll add you to our Git, and the main place we communicate is on the platform the links above point to. There's a getting started guide in the Reactjs section.
> 
> Welcome :)

Thanks! Also thanks a lot for the warm welcome!

I'll be using the forum for communication from now and onwards, so I think we can safely close this issue.

🙌
