### ISSUE TITLE
Add UI to edit text (if user is an admin) in the front-end

### ISSUE THREAD

**Issue by ydaniel98** [focallocal/fl-maps#113]
The front end code is done for the most part. It's on this branch: https://github.com/ydaniel98/fl-maps/tree/text_018n_enable. Check the file https://github.com/ydaniel98/fl-maps/blob/text_018n_enable/client/commun/adminEditHandler.js.
I would also suggest using i18n-db.

**Comment by AndyatFocallocal** [comment]
closed issue. great job its an excellent solution
