### ISSUE TITLE
Change hardcoded api to one in settings.json

### ISSUE THREAD

**Issue by ydaniel98** [focallocal/fl-maps#117]

**Comment by AndyatFocallocal** [comment]
can i ask about the status of this issue as i don't fully understand it's implications. is this something that needs to be complete before Alpha launch? :)

**Comment by ydaniel98** [comment]
@AndyatFocallocal No, we cannot launch without this. It should be a 10 minutes thing. Currently I'm prioritising bringing admin mode back.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 ok :)
