### ISSUE TITLE
bug: remove green panel recently added behind + (add gather/resource) button

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#128]

**Comment by Spartano** [comment]
Its not a bug. I have added it, lol. I was tryng to evidentiate the create
event. How would you like to change it?


Il 21 Feb 2017 23:43, "AndyatFocallocal" <notifications@github.com> ha
scritto:

**Comment by AndyatFocallocal** [comment]
Maybe an outer glow around the button

**Comment by AndyatFocallocal** [comment]
I thought the text opening when the user visited handled it pretty well, we can run a few tests and return to this in the Beta launch

**Comment by Spartano** [comment]
I will set it opacity 0.1 then

Il 22 Feb 2017 11:46, "AndyatFocallocal" <notifications@github.com> ha
scritto:
