### ISSUE TITLE
times displayed are an hour ahead of times selected

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#20]

**Comment by mordka** [comment]
Ha it's a good catch. We have internationalization problem.
When user selects a date and save form -> the date should be converted from user's timezone the UTC and saved to database (https://github.com/mordka/fl-events/blob/master/both/collections/events.js#L211)
When user is displayed a date we should read the date from database and convert it to user's timezone.
(various places in the app)
This can be a good reference for this problem:
https://themeteorchef.com/snippets/handling-timezones/

**Comment by AndyatFocallocal** [comment]
If possible it would be better to simply have the time selected as the time selected, ignoring time zones. Facebook does this and it regularly causes issues for event organisers who are travelling (as a lot of ours will be), using a proxy, daylight savings changes, or just computer weirdness going on. 

low tech, select a time, get a time is better

![image](https://cloud.githubusercontent.com/assets/16229696/17343743/29e359e8-58f7-11e6-9704-eeb06b40b5d4.png)

**Comment by ydaniel98** [comment]
@AndyatFocallocal How about a small popup on top of the page prompting the user to select a time zone (it would be saved as a user setting)? Also, the time zone could be specified where ever the time is displayed on the page.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i'm ok with that suggestion, if an automatic option is difficult or likely to have bugs

**Comment by mordka** [comment]
@ydaniel98 times are displayed in user's timezone by default so I don't see a point of selecting it ;)

**Comment by AndyatFocallocal** [comment]
@mordka Facebook has a lot of troubles with this system when people are travelling as it puts their profiles default timezone in when they create an event (i triple check after creating an event on the road). 

the Gatherings map is going to used often by traveller wanting to meet people and do positive action together. where does the current auto-selected time zone get the time zone from?

if its a risk, simply having users select the time they want their event to start, and just ignoring time zones entirely, when creating and viewing events would be fine. simple and no risk of problems later. its says its 3pm, its 3pm. no matter where you are viewing from.

**Comment by ydaniel98** [comment]
@AndyatFocallocal @mordka I have not been able to find anything related to time zones in the code. It seems like they have not been taking into account at all.

**Comment by mordka** [comment]
The date should be saved in UTC format into database, when client is reading
the date it converts to it's timezone. it's a browsers feature
--
Pawel






On Thu, Jan 19, 2017 8:21 AM, Edwin Daniel Penalo notifications@github.com
wrote:
@AndyatFocallocal  @mordka  I have not been able to find anything related to
time zones in the code. It seems like they have not been taking into account at
all.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 @mordka  my recommendation is just to shut this operation down. far simpler and no risks of issues relating to vpns or travel causing times to be set wrong, if we just save times purely in numerical format. 

As an event organiser with FL for 5 years, i am repeatedly messed around by facebook, couchsurfing, meetup, etc, trying to predict what time zone i want my event in, or giving me the wrong details for an event in another country because i'm viewing it in from UK (or my computer still thinks its in the UK). 

if it put 15:00, that's what i mean. if i read 15:00 thats what i expect.

**Comment by ydaniel98** [comment]
@mordka Thanks, I didn't know it was a browser feature.
@AndyatFocallocal The fix was quite easy and no db modifications were required. If timezones are needed in the future, it should be quite easy to implement.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 awesome! ᕙ༼ ,,ԾܫԾ,, ༽ᕗ
