### ISSUE TITLE
Report button sends report to admins

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#309]
currently the report button in each activity/resource listed is not operational, leaving us open to abuse. this task is urgent, but might require user levels and mods to be implemented 1st

**Comment by ydaniel98** [comment]
@AndyatFocallocal An email or on-site message? Also, we can implement it with admins only first and then make it more complex later.

**Comment by AndyatFocallocal** [comment]
admins 1st would be fine. i'd say emails would be faster

**Comment by AndyatFocallocal** [comment]
@ydaniel98 maybe both actually, so in the future admins and mods can choose which they'd prefer

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'll increase the functionality of the admin dashboard.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i dont receive notifications here (not sure why). better to contact me on the discuss forum
