### ISSUE TITLE
All text editable in admin area (label, <h>, intro)

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#31]
The Best solution would be to add fields into the admin area (backend/godmode) where an admin can change all text areas in the map. 

If you prefer to fork the project and code the titles yourself here are the changes required: 
- times changed to 'start time and finish time' (so visitors know when resource opens and closes)
- Add 'StreetSleeper Resource Map' Title to Menu
- 'Create your Gather' + icon on home page. pop up text changed to 'Free Resource'
- Intro page text updated, i'll write some text when someone is ready to work on this. it will be roughly the same amount of words as the map's current home page so redesign is not necessary

**current 'create your gather' window changes:**

1 New gather : free resource
2 Choose event category : resource category
3 Event name : Resource Name
4 Address or postcode : -unchanged-
5 Meeting point : -remove-
6 How to find us? : How to find/access resource
7 Date of the event : Opening Days
8 Hour : Opening Hours
9 Description : -unchanged-

**Comment by AndyatFocallocal** [comment]
An alternative, and more useful solution for this map in long-term, would be to make all headings editable in the backend (godmode), so it was easy to edit this map and redeploy it for other projects

**Comment by AndyatFocallocal** [comment]
![icons](https://cloud.githubusercontent.com/assets/16229696/17342840/f778767c-58f2-11e6-9490-9c88f366a8a7.png)
![image](https://cloud.githubusercontent.com/assets/16229696/17342857/0e44b208-58f3-11e6-9cc4-a30a3ac492b8.png)
![image](https://cloud.githubusercontent.com/assets/16229696/17342864/11298e58-58f3-11e6-9ce7-e274e7ccb0eb.png)

**Comment by AndyatFocallocal** [comment]
![icons](https://cloud.githubusercontent.com/assets/16229696/17342974/6bf54bf6-58f3-11e6-86a0-6f5624060f9b.png)

**Comment by AndyatFocallocal** [comment]
![text 2](https://cloud.githubusercontent.com/assets/16229696/17343030/b5aa6a88-58f3-11e6-81de-b6847b9d80f2.png)

**Comment by AndyatFocallocal** [comment]
![text 2](https://cloud.githubusercontent.com/assets/16229696/17343071/e01db7c0-58f3-11e6-8837-6bcbf9b0d237.png)

**Comment by AndyatFocallocal** [comment]
![text edit](https://cloud.githubusercontent.com/assets/16229696/17343456/aca38026-58f5-11e6-9006-7978276b8247.png)

**Comment by AndyatFocallocal** [comment]
@maypo are you still active on this issue? if not would you mind un-assigning it so it doesn't hold others back from working on it

**Comment by ydaniel98** [comment]
@AndyatFocallocal. @Spartano added the package and figured out how to use it. I'll populate the json file.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 Its the stuff of legends!

**Comment by ydaniel98** [comment]
@AndyatFocallocal. @Spartano too, he came up with the idea :).

**Comment by AndyatFocallocal** [comment]
@Spartano also a legend! :)

btw, does this mean i'm not needed for the screen share on Sunday, or is that separate?

**Comment by ydaniel98** [comment]
@AndyatFocallocal From what I understand, currently since there is no ui for it, the text has to be edited in the back-end. Until then, it would be useful if you could also perform edits.

@Spartano Is that right, or did I misunderstand?

**Comment by Spartano** [comment]
Yes, the text hAs to be changed in the code, but it is very easy to do it.
In 2 min with a screen share i can teach you, so you can change it at will

Il 16 Feb 2017 10:47 PM, "Edwin Daniel Penalo" <notifications@github.com>
ha scritto:
