### ISSUE TITLE
change entry's to only list on map when user completes entry forms

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#319]
currently if a user begins, completes a few modals, then gets board and stops. the system still creates a listing. please change that to only when a user completes the last modal window (before the share your activity pop up)

**Comment by ydaniel98** [comment]
@AndyatFocallocal Could you specify what you mean? I couldn't replicate it.

**Comment by AndyatFocallocal** [comment]
i think it may be resolved. i was finding that if i begun creating a event and then stopped at modal window 4 for example, it would create a half finished event. i haven't noticed that in the last week so i think its fixed
