### ISSUE TITLE
'pick a time' not allowing users to pick a time later than 13:00

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#32]
maybe screen size/resolution dependant. when i scroll down the furthest i can go is 13:00 and anything after 10am isn't intuative to access as the pointer is below its window

**Comment by AndyatFocallocal** [comment]
![event time select](https://cloud.githubusercontent.com/assets/16229696/17342666/2acf78dc-58f2-11e6-8687-f4790f541622.png)

**Comment by alfiepoleon** [comment]
All the time is in the html file, but scrolling doesn't seem to go to the last option 2330, in my screen it goes up to 1900. 
Maybe a height issue in the div? I'll look at it later today

**Comment by zmikaya** [comment]
I think it fails to properly account for screen size, so on a larger
screen, you see more values.

**Comment by iggelt** [comment]
The problem is that size of list  (<ul>) is too big and it owerflows the event form.  changing max-height to 200px for class .dropdown-content solves this problem
