### ISSUE TITLE
Routing Main Board After First Time Register Should have been showing register form again.

### ISSUE THREAD

**Issue by nsrtky** [focallocal/fl-maps#321]
after completing registration then we dont need register form,which is blue background color at sing-in route.
i am going to share its prntscrn. 

![image](https://user-images.githubusercontent.com/12385044/27761948-110c529c-5e70-11e7-97b3-728c63c35d64.png)

**Comment by AndyatFocallocal** [comment]
that's the login screen for the news site and the forums. 

we've sync'd the login on news.focallocal.org and discuss.focallocal.org, but haven't sync'd that with the maps yet. i'd love to get it done, but it is a large task

i've read that the login pages dislike that we aren't using SSL and that might be causing problems. if not i'll have a look around and see if i can see how to redirect back to the page we came from. apparently its an easy job: https://meta.discourse.org/t/its-a-real-struggle-to-move-my-team-across-from-slack-they-miss-the-mobile-notifications-how-did-you-solve-this/65135/3

**Comment by AndyatFocallocal** [comment]
This issue was moved to AndyatFocallocal/temp#23
