### ISSUE TITLE
When New Gather Need Help Link Not Working. 404 

### ISSUE THREAD

**Issue by nsrtky** [focallocal/fl-maps#322]
We need update need help its realy usefull at the beging.

![image](https://user-images.githubusercontent.com/12385044/27762029-898a50ba-5e71-11e7-9070-7f314d7b39f7.png)

**Comment by AndyatFocallocal** [comment]
@nsrtky 
ah yes. we need to create a guide there. its on the task list. i'll set up a placeholder page at that address now to help

**Comment by AndyatFocallocal** [comment]
This issue was moved to AndyatFocallocal/temp#22
