### ISSUE TITLE
New Gather Address Field Not Accepting Turkey,İstanbul,Bebek...

### ISSUE THREAD

**Issue by nsrtky** [focallocal/fl-maps#323]
İ have not able to create a new gather at the address screenshot is below ? Does anyone has similar problem ?

![image](https://user-images.githubusercontent.com/12385044/27762041-ee082d96-5e71-11e7-8670-cdba76d26485.png)

**Comment by AndyatFocallocal** [comment]
@nsrtky i think you'll need to add a street address or post code there

**Comment by nsrtky** [comment]
i have deactive address checking at event.js so we are able to add new gather at the moment. May this will have been a work around solution at the moment by time we can solve checking also

![image](https://user-images.githubusercontent.com/12385044/27769623-a4d7e7fe-5f36-11e7-8f3e-9abcca01151c.png)

**Comment by AndyatFocallocal** [comment]
ok. can you create a pull request?

**Comment by nsrtky** [comment]
may you tell me which button or link at which are of web app should have be able to pull request? if you ask for git hup ı have uploaded the codes at my fork over server ? https://github.com/nsrtky/fl-maps/commit/9017e7d372dcb6c5f0e12bd8e4ac3e27de901361

**Comment by ydaniel98** [comment]
@nsrtky @AndyatFocallocal This seems to have been fixed.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 in a sense yes, and in another sense no. the issue really is that different cultures enter addresses in different formats. Greg is having a look at a solution, which i think will probably end up by asking for each element separately. street, town, house number, etc
