### ISSUE TITLE
Creating Gather Give Address Error at eventsForm.js line 18

### ISSUE THREAD

**Issue by nsrtky** [focallocal/fl-maps#325]
ı have tried creating new gather than filled textfields as below but not let me cos of address its taking place at eventsForm.js 18 lines.

![image](https://user-images.githubusercontent.com/12385044/27765245-397cea94-5eb5-11e7-958d-205d47d1961f.png)

![image](https://user-images.githubusercontent.com/12385044/27765235-fd59760e-5eb4-11e7-87b1-a9400d885b7e.png)

**Comment by nsrtky** [comment]
i have tried to connect mongodb via below tool but its not working does any one achieve to connect meteor mongodb collections?
it has told us coordinate required but undefined ?

![image](https://user-images.githubusercontent.com/12385044/27769400-29308570-5f31-11e7-855a-b3f52ad07dbb.png)

the tool i have wanted to see collection in project ?
![image](https://user-images.githubusercontent.com/12385044/27769358-7aabb182-5f30-11e7-8bbe-bf80aaa24bc3.png)

**Comment by AndyatFocallocal** [comment]
@nsrtky please post in the forum and tag @ydaniel98 and @Spartano as they may be familiar with the issue. thank you

http://discuss.focallocal.org/t/meteor-maps/165/140

**Comment by Spartano** [comment]
try this, https://stackoverflow.com/questions/27190633/robomongo-connection-with-meteor-mongodb

**Comment by AndyatFocallocal** [comment]
This issue was moved to AndyatFocallocal/temp#20
