### ISSUE TITLE
(updated) Improving text management and entry on 'Overview' and 'Full Details'

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#33]
overflow issue requiring a scroll bar or text cut off

**Comment by AndyatFocallocal** [comment]
![bouncing](https://cloud.githubusercontent.com/assets/16229696/17342479/70fa2d44-58f1-11e6-842c-ae92200c5a63.png)

**Comment by Pierre-Ferreira** [comment]
Hi Andy. I was able to replicate this issue (the whole screen bouncing) on my local machine yesterday, but today it is working fine. Bit of a slippery fish.

**Comment by AndyatFocallocal** [comment]
Sorry @Pierre-Ferreira i don't get notifications from comments at the moment unless you tag me. Not sure why, i'll try to change that

it seems to happen when either the description is too long, or when the screen is too small for the text in the description. i think that's what causes it

**Comment by ydaniel98** [comment]
@AndyatFocallocal. I was not able to replicate this issue. Maybe it got fixed?

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i would double check but it seems the fixes are not being pushed to the live map, so i'm still not able to create gathers/resources there/ have asked @mordka @distalx if they can see the issue

**Comment by ydaniel98** [comment]
@AndyatFocallocal I checked the live map, and I was able to create an event. Not sure of what's going on.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 it seems the issue is with Post/Zip codes only, which is something that might be best to deal with when tackling issue #57

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i've got it working and it looks as though someone has half-solved this bug by making the site cut the description after a set amount of words. 

the issue previously was that long descriptions made the pop up try to expand outside the main screen window, after clicking on a dot. causing the whole screen to bounce up and down rapidly as it tried to show everything

the solution active now of cutting the text off is not complete. it doesn't inform the user that text will be cut, or stop them from writing more when they reach the word limit. also the current limit is too small.

My suggestion would be to add two text boxes, an 'overview' and a 'full description'

- the overview would appear on the pop up (the current word limit is fine for the overview)

- both would be visible after clicking 'show more'

the full description word limit would be ..perhaps 4 times the length of the overview

we'd then need to stop the text entry box from accepting words after the limit is reached, and add text informing the user of the limit, like a character count.

something like this:

![temp text bix](https://cloud.githubusercontent.com/assets/16229696/21967613/7cbaf0dc-db82-11e6-9ab4-31af834e705d.jpg)

**Comment by AndyatFocallocal** [comment]
just tested it. appears to be working beautifully, and i think the character count balance is just about perfect :)
