### ISSUE TITLE
Printable maps

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#35]
Note: this feature does not need to be implemented before the project launches.

We want users to be able to print out a physical copy of resources on the map, so they can give it to people near them who are homeless

the printout will include: 

1. a map view with all icons visible to the user when 'print' is clicked
2. a key 
3. a list of details (suggestion bottom half of page, or on a second page if the split screen view is too small to read)
including:
   - Title
   - Resource/Activity Type
   - Address
   - Date and Time

Suggestion split top and half and bottom of A4 Page. If that is too small to be easily usable then they'd print on separate pages. If possible to send setting to a printer our recommended setting would be to print front and back on one sheet

... 

Presumably when printing the icons and list would need to add numbers to match icons to details in the list. 

If possible the 'print' button should only appear when map is zoomed in to a usable distance. say london size and lower. perhaps 1/4 london size

**Comment by Angamanga** [comment]
Maybe there are some useful information here: https://northlandia.wordpress.com/2016/03/16/printing-in-leaflet/

**Comment by fossilblue** [comment]
Hi,

Will try to research on this one.

**Comment by fossilblue** [comment]
Still checking this on GitHub https://github.com/rowanwins/leaflet-easyPrint

Any comments?

**Comment by AndyatFocallocal** [comment]
@fossilblue Looks good. It would require the ability to print a map and list, of what is currently on the users screen so user can choose which location and which resources it they print. this would include/exclude filters which are currently selected

**Comment by AndyatFocallocal** [comment]
Added to alpha incase someone wants to work on a task but there are none left. this is not required for Alpha launch

**Comment by ydaniel98** [comment]
@AndyatFocallocal This is mainly just a button and a few css media queries.

**Comment by ydaniel98** [comment]
@AndyatFocallocal 
[print-beta-1.pdf](https://github.com/focallocal/fl-maps/files/1163174/print-beta-1.pdf)

**Comment by AndyatFocallocal** [comment]
@ydaniel98 good start. its going to need issues solved;

1) printing in colour is expensive, but our legend is useless without it. perhaps converting the dots and legend icon colours into numbers when printing would be possible so users could print in greyscale?

2) we'd also want "name", "address", "category" and "opening hours" to print in a list below the map, or on the next page/s, pulling those details from each dot printed. oh, also the name of the map and the web address so they can find it online

**Comment by AndyatFocallocal** [comment]
obviously we'd need to cap the maximum number of listings printed, either by ignoring over a value, or advising users to use filters to reduce the number. 

in case someone decided to print the World map and there were 20,000 or so listings it printed
