### ISSUE TITLE
text fields overlapping

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#390]
![image](https://user-images.githubusercontent.com/16229696/28927178-c75e5788-7861-11e7-9ef2-9d17d59b52a4.png)

**Comment by AndyatFocallocal** [comment]
@ydaniel98 remember to close issues so others don't repeat your excellent work

**Comment by ydaniel98** [comment]
@AndyatFocallocal I haven't fixed this one

**Comment by ydaniel98** [comment]
I fixed the text overlap in home.html when viewing on mobile.

**Comment by AndyatFocallocal** [comment]
sorry my mistake. the title was similar to this one: https://github.com/focallocal/fl-maps/pull/393#event-1197444735
