### ISSUE TITLE
're-assign correct main menu icons

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#40]
Email me: contract@focallocal.org 

I have a screenshot from before the library became messed up

**Comment by alfiepoleon** [comment]
How was it before?

**Comment by AndyatFocallocal** [comment]
Here's the right half: https://drive.google.com/file/d/0BwLUtixxA6u_VGt6STlORWVDRFk/view?usp=drivesdk

And here's the left half: http://focallocal.org

**Comment by AndyatFocallocal** [comment]
Also, this should be a + sign

![icons](https://cloud.githubusercontent.com/assets/16229696/17342774/9fd59f12-58f2-11e6-9a18-7d55e44805d6.png)

**Comment by AndyatFocallocal** [comment]
Delete and Edit are not the correct icons. Screenshot of originals not available so you'll need to select accurate new icons

![dialogue box](https://cloud.githubusercontent.com/assets/16229696/17343245/956ffbf6-58f4-11e6-8447-50205a510434.png)

**Comment by AndyatFocallocal** [comment]
@ydaniel98 thanks for linking these together :+1:
