### ISSUE TITLE
Add forgotten password reset system

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#47]

**Comment by fossilblue** [comment]
Can I do this one?

**Comment by fossilblue** [comment]
Added the forgot and reset password.

**Comment by AndyatFocallocal** [comment]
@fossilblue absolutely, if you are still interested there are a few developers pushing towards that launch we've been talking about.

best to communicate primarily on Slack though as i don't get notifications here (..can't work out why)

**Comment by AndyatFocallocal** [comment]
i didnt hear back from @fossilblue about his post above. this issue may be resolved already

**Comment by AndyatFocallocal** [comment]
it seems this issue has been started but i'm not aware if its complete or not. if taking this you can have a look at the code here: https://github.com/focallocal/fl-maps/pull/54

it might already be sufficient, or a starting point that'll save some time

**Comment by Spartano** [comment]
dont know if it will work because i dont know Blaze so good, lets leave it
for now, i will try to implement it on saturday.

**Comment by AndyatFocallocal** [comment]
closed as i believe Spartano solved this today
