### ISSUE TITLE
Double click on a dot is supposed to auto-zoom in. the function appears to have broken

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#48]

**Comment by Angamanga** [comment]
@AndyatFocallocal When I run the application, it does auto-zoom, not very far though, do you want it to zoom longer than it currently does?

**Comment by AndyatFocallocal** [comment]
oh, i'm not receiving notifications it seems. i'm sorry @Angamanga. it should zoom in to show roughly the area of a large city like London. tbh, i cant check as the live version appears to be not working at all
