### ISSUE TITLE
Add Menu icon on the left titled 'Uni' 

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#50]
Add a menu icon on the left titled 'Uni', in full it will be Focallocal University of Positive Action

url will be http://uni.focallocal.org

this is for a University Course i will be setting up to teach people how to do what i do, to work on and create some awesome projects together, and have their name and photo up on our website as a graduate, and in the projects they led, or worked on. 

it won't be a real degree (for now), but it will look damn impressive on a CV/Resume, being able to point to what they made happen, and help our project build/maintain an active pro-active team 

(initially it'll point to a placeholder page. the Uni is a project i plan to build this winter)

**Comment by AndyatFocallocal** [comment]
@alfiepoleon i've assigned you as i know you were working on the Menu anyway. No worries if you'd rather not, just seemed that this should be linked to the tasks you were working on

**Comment by erostatyka** [comment]
Nice!

W dniu niedziela, 7 sierpnia 2016 AndyatFocallocal <notifications@github.com>
napisał(a):

**Comment by AndyatFocallocal** [comment]
My suggestion would be a Graduation Cap, like this one: http://fontawesome.io/icon/graduation-cap/

Although we aren't using font-awesome as yet

**Comment by AndyatFocallocal** [comment]
@erostatyka nice that you're still following the project. we've got a great team together and working on it now and you'd be welcome to join in again if you like, just let me know and ill invite you to our Slack group :)
