### ISSUE TITLE
Remove modal window 5

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#526]
it repeats window 4 too closely making it redundant

![image](https://user-images.githubusercontent.com/16229696/39401934-ea3e6246-4b49-11e8-83f9-7409ff32290c.png)

**Comment by royGil** [comment]
fixed #539

**Comment by AndyatFocallocal** [comment]
nice. it's a small annoyance gone. please can you find the card for issues you solve in https://trello.com/b/PFj7RlgM/focallocalorg and move them into mission complete

thanks @royGil

**Comment by royGil** [comment]
@AndyatFocallocal 

Done
