### ISSUE TITLE
Time date modal redesign/build

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#549]
the struggles comes because the map is designed for:

steady resources, like a shelter open 7 days/week for the forseeable future

resources open a few days a week, and at different times. 
tues, weds, fri. 
08:00 - 13:00
09:30 - 14:00
07:00 - 12:00

one off resources like a week long special event, or just on one day like a yearly soup kitchen at xmas

recurring resources like a user offering CV help, or life counselling in a local library one a week or month on the 1st Tuesday of the month, or the 15th of each month

**Comment by AndyatFocallocal** [comment]
[New time+date module.pdf](https://github.com/focallocal/fl-maps/files/2014362/New.time.date.module.pdf)

**Comment by royGil** [comment]
You can follow [this](https://github.com/focallocal/fl-maps/tree/datetime-module) branch and try it locally - it's almost ready.
