### ISSUE TITLE
remove icons from the map which aren't our icons

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#552]
our icons are hard to see as they are swamped by google's places of interest so we need to hide google's

unfortunately, i set this up a few years back and have no recollection how i did it. if its not instantly apparent contact me and we can work on it together. if i can find the service i used, and where the code goes in our build then it's just a case of clicking an icon and copy/pasting the new code in. 

i saved it there as a project.

![image](https://user-images.githubusercontent.com/16229696/40269527-bd70d53a-5b77-11e8-8efd-15ea7d2644f3.png)

**Comment by royGil** [comment]
What about just changing our icons into something more unique? we can use a different shape/size..
Google's icons can actually be helpful for people to find the events no?

**Comment by AndyatFocallocal** [comment]
Yes, I'd like to do that as we have too many categories for the current
system, especially when we add the ability to select multiple categories on
a listing. We could perhaps have the multicoloured with all the categories
selected.

I still want to remove the google icons, they clutter the map and reduce
the focus on our icons. I'll try to get the code without them and send it
over to be added

On 19 May 2018 15:46, "Roy Giladi" <notifications@github.com> wrote:

What about just changing our icons into something more unique? we can use a
different shape/size..
Google's icons can actually be helpful for people to find the events no?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/focallocal/fl-maps/issues/552#issuecomment-390409813>,
or mute the thread

**Comment by royGil** [comment]
This is how it's done - https://github.com/focallocal/fl-maps/blob/react-maps/imports/client/ui/pages/Map/mapStyles.js#L26
