### ISSUE TITLE
test z-index on different screen sizes

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#565]
![image](https://user-images.githubusercontent.com/16229696/40364056-3560499c-5dc9-11e8-8ce7-e4d914c4d3ef.png)

mobile looks fine to me, although i've only tested it lightly. desktop on unusual screen sizes has some elements appearing obscuring more important ones as in the image above. it would be good to evaluate and edit their z-index. 

i noticed the activity popup being hidden behind the search bar and filters lists.

**Comment by royGil** [comment]
this is the default behavior of google-maps..
I don't think we can control that but let me know if you stumble upon a map which displays the popup on top of the other elements..

**Comment by roamingandy** [comment]
if you've set the filter window to be full screen and it's on top of all 
other elements then that will be fine. just the search bar which is a 
bit ugly when on top of the activity popup. we may need to move back to 
openmaps at some point in the future as apparently google has high 
charges when you get over a certain amount of requests/day.

i'm unclear on how that will manifest, and we are a long way off from 
that number of users at them moment, so i don't think it's something we 
should spend time working on at this point in time. once the map is 
launched we'll be attracting more developers in to carry on the build 
and look at issues like that which will occur later on.
