### ISSUE TITLE
redesign of 'gathering'/'resource' creation window.

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#57]
one of the main purposes of the Gatherings Map is to take away the fear of creating an event yourself. people worry it'll be hard, so presenting them with a wall of options to enter will put many people off. similarly less people will want to enter all the details of a resource if it looks like it'll take a long time. 

we want to walk them through it step by step, so upon clicking 'add a new resource/gathering' users will be met by a popup window with one field to enter.

all text areas will be editable in the backend by an admin, but here is the path users will take in the 'Gather' map, as an example.

popup windows:
>1. Choose a Category
>Not sure? Here's a list of suggestions: news.focallocal.org/activities 
>(if the Positive Action you want to create isn't there let us know at contact@focallocal.org) 
> Give your Gathering a name 
> 
>2. Select a City
>
> 3. Choose a Date and Time 
> 
> 4. Enter address or postcode/zip - or choose from commonly used meeting points in that city, 
(clicking on a commonly used point auto-fills that location into the text entry box). 
> 
> 5. Choose a specific meeting point  (hidden on street sleeper map)
> Text: Be as specific as possible. Next to a statue? North, West of a bridge? Not sure? Check Google Earth for a good meeting spot. 
- if using a 'commonly used meeting point' this should be auto-filled, but editable by the Gathering creator 
> 
> 6. How will people recognise you? (hidden on street sleeper map)
> Carrying a Teddy Bear on your Shoulder? Wearing a bright yellow hat? wearing a Focallocal badge or T-shirt? 
> 
> 7. Description/More Details
> Gatherings map should auto include some default text about the gathering in the description pulled from a template. Users can then edit and add to this. right now the text is at http://news.focallocal.org/activities descriptions should be edited by Andy for the purpose, and then submitted to gather, and linked to the correct gathering, via an entry box in the admin area

**Comment by AndyatFocallocal** [comment]
note: the address system has been turned off, and addresses are only allowed by city. part of this issue will involve switching them back on again

**Comment by ydaniel98** [comment]
@AndyatFocallocal What do you mean by that? I tested entering an address and it worked just fine.

**Comment by AndyatFocallocal** [comment]
cant find a prominent address in London

![image](https://cloud.githubusercontent.com/assets/16229696/22347026/2d9999a2-e3fe-11e6-97a1-aff506d4df35.png)

Seems to be arguing with my auto fill

![image](https://cloud.githubusercontent.com/assets/16229696/22347047/49e41bfa-e3fe-11e6-9ba1-f6736f0cc826.png)

it did intermittently attempt to suggest a location using the Maps system, but i couldn't get it to load most of the time

![image](https://cloud.githubusercontent.com/assets/16229696/22347218/088ab29e-e3ff-11e6-82a3-b473fd9df0b5.png)

some times i was able to have suggested US addresses, but not european ones

![image](https://cloud.githubusercontent.com/assets/16229696/22347263/3f94a33a-e3ff-11e6-9a0f-343d77922ffc.png)

**Comment by AndyatFocallocal** [comment]
note: the map did previously work for all locations and addresses, so something has been changed, or is interfering with the system. any idea what could cause this @mordka and @distalx ?

**Comment by ydaniel98** [comment]
@AndyatFocallocal I would suggest not including this in the Milestone for the Beta. It's taking a lot of refactoring and could bring about a few bugs a side effect. 

Also, since the form is automatically generated that complicates everything a bit.

**Comment by mordka** [comment]
@AndyatFocallocal I fixed it now, could you test again?

**Comment by ydaniel98** [comment]
@AndyatFocallocal How about keeping the current form factor for errors? The form factor you described would be implemented, but if the form has any errors then the slide form would be shown with the errors. Then the user can review the data and then submit again.

@mordka Do you know how we could work around Autoform? Or do you think we should not use it at all?

I'm not gonna have a reliable internet connection for the next few days. I'll try to get some work done on this one on Tuesday.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 we'll get a significantly higher drop off rate with the current form, users look at it and decide to put it off to another time. where as the chain of single/double entry windows means they've made a commitment after the 1st box and are much more likely to complete the submission.

we will also need to make changes to this before Beta launch anyway as its currently set up for gatherings, rather than being editable for gatherings or resources. 

if you think its not possible in time for Beta launch you are welcome to find a workable shortcut. also consider asking @channel in Slack for support. there are a lot of developers who while inactive mainly, they seem keen to support when reached out to with an issue

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'll try a few more things on Tuesday, but I'll certainly be asking for support in slack. 

Thanks.

**Comment by ydaniel98** [comment]
@AndyatFocallocal I made significant progress. I think that this issue will be done by tomorrow or Thursday.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 thank you so much! i was expecting a few more Meteor dev's to join in leading up to our Hack Weekend, but they never materialised. If it wasn't for your efforts we would have little chance of launching, and be working on a far more fragmented project.

Will you be joining in this weekend also? :0)

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'm happy to help :). I don't know If I'll join for sure but I will try. I'm in a very different timezone.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 awesome. a few of the guys here have requested we make it a 38hr hack with coding all night so there might/should be people online at the same time as you. 

head over to the forum we set up for it and say Hi. tell people a little about the amazing work you've been doing here in Github, and your skills :0)

http://discuss.focallocal.org/t/introductions-homelessness-and-happiness-hack-heros/72

**Comment by AndyatFocallocal** [comment]
@ydaniel98 we're hacking. can we contact you if you're online please :)

**Comment by AndyatFocallocal** [comment]
@ydaniel98  we'd really like your knowledge of the map code with some edits they've made. they think it would be a far smaller task for you as you understand the code on here now.

there were some broken issues in the map, and no addresses, so they'd like to change the map for a Google maps one, and have three files which you should be able to modify to load the data from the database (as now the data is hardcoded there). things have been a little slow but we are making progress. 

the files for the map are here https://github.com/rnosov/map

**Comment by ydaniel98** [comment]
@AndyatFocallocal I did some work earlier, but unfortunately right now I'm busy. I'll be happy to help tomorrow. Just let me know.

Also, I think using google maps is a great idea.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 that's awesome! we'll be online from 9.30am GMT. how can we reach you? can we communicate via the forum? 

http://discuss.focallocal.org/c/hack-homelessness-and-happiness/meteor-dev-brighter-tomorrows-gathering-map

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'm online now. We can communicate through slack, here on github, or the forum. Which ever is easier.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 sorry, i missed this as i don;t get email notifications form any of those.

i didnt want to set my accounts up in any way that was different than an average user, so our own forum should be best but there is some kind of an issue that i can't find preventing the emails going

**Comment by ydaniel98** [comment]
@AndyatFocallocal Any feedback on this? Or do you consider this issue solved?

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i'd consider this closed. i just kept the thread open as it had the map files in the comments. if you have those go ahead and close the issue! 

thank you, i'm not giving up on this map and letting a cheap imitation take away the benefit it was going to bring to people on the streets around the World
