### ISSUE TITLE
Current databases copied/merged with React version databases

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#575]
there isn't a lot on either map atm fortunately. although what is there was uploaded by members of each community, and we don't want anyone thinking their efforts were wasted

**Comment by royGil** [comment]
i'll work on that once we push that version live

**Comment by AndyatFocallocal** [comment]
cool :)

**Comment by royGil** [comment]
done, once we push the new version i'll update the server's db
