### ISSUE TITLE
unexpected token error when trying to post activity/resource

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#579]
path: 
free hugs (auto-filled from yesterday)
just one day
all fields entered
error message: please check that you've filled in all necessary fields (a message saying which one i've missed would be helpful as a user)

solution: changing the address. so it worked, but the pre-loaded address from past effort had an error

![image](https://user-images.githubusercontent.com/16229696/40491518-31cd0416-5f66-11e8-888a-27f75a0b33a6.png)

location related error message

![image](https://user-images.githubusercontent.com/16229696/40491664-9017297a-5f66-11e8-9fe4-1d0912624d10.png)

**Comment by royGil** [comment]
fixed with #590
