### ISSUE TITLE
small line added in Megamenu to show users which area of the site they are currently on

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#584]
(focallocal.org required only as most icons are hidden on the brighter tomorrow map_

the number of icons is confusing to some users. simply adding a little line underneath the icon for the area of the site they are currently on will add a visual cue that its a representation of where they are. small change, but UX/UI team think it'll make users feel more at ease.

**Comment by royGil** [comment]
fixed
