### ISSUE TITLE
Can't add events (Typeahead not working)

### ISSUE THREAD

**Issue by ydaniel98** [focallocal/fl-maps#59]
When the new event formed is properly filled out, the event is not added.

**Comment by ydaniel98** [comment]
@AndyatFocallocal @mordka I checked a few previous commits and the issue seems to be present in month old commits.  Is it known when the issue first appear?

**Comment by ydaniel98** [comment]
The problem seems to be here (eventsForm.js): 
`if (instance.debounce) {
            Meteor.clearTimeout(instance.debounce);
  }`
`instance.debounce is not defined`
However, this error only shows up sometimes. I think it's due to meteor-typeahead not working properly.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 good tracking down. 

We had a team form and work on the Map but activity slowed and didn't come back until now, so its been close to dead for about 2 months now. the issue would most likely have come about when we upgraded the system to Meteor 1.3. 

a 1.4. upgrade has been suggested as a side project that people can play around with once the map is live. its expected to bring about more breaking changes, and right now we really just want to get those issues in the Brighter Tomorrow Milestones crossed off so the map can launch and begin growing, while further development goes on

**Comment by ydaniel98** [comment]
@mordka The problem seems to be typeahead. I am not sure of how to fix it. I've tried several things but it keeps behaving erratically. Do you have any idea of how to fix it?

**Comment by ydaniel98** [comment]
I tracked down the problem withing typeahead. It occurs in line 2587: `template.$(selector).each(init_typeahead);`. JQuery, sometimes, returns an empty object which causes typeahead to not initialize properly.

**Comment by ydaniel98** [comment]
I managed to fix the bug, but typeahead is still not working 100%. I had to use a bit of a workaround for autocompletion to work (typeahead, I think, is conflicting with another package) after fixing the original problem, but now, once the option is selected, there is another error withing typeahead. Should I create a PR with the progress I've made so far? I could use a little help.

**Comment by distalx** [comment]
Thinking out loud here. If we use the new directory structure would that be helpful? what I understood so far is that sometimes JQuery takes time to load and if typeahead tries to initialize during that time it causes this issue !
with use of the `imports` pattern we would be able to control the load order.

**Comment by ydaniel98** [comment]
Hi @distalx. What was happening is that autoform was loading after `eventsForm.onRendered` was triggered, that caused JQuery to return an empty object. I fixed it by initializing typeahead inside `autoForm.onRendered`. With that and a bit of a workaround, typeahead started displaying suggestions but throws an error after selecting one (No idea why).

Anyways, I think it would be a good idea to use that structure.

**Comment by ydaniel98** [comment]
I created a pull request for this issue. It turns out that typeahead had not been updated in a while. I thought I updated it when I started working on this issue, but I hadn't.

Also, @distalx How about we creating an issue for import patterns. I think it could facilitate debugging in the future.
