### ISSUE TITLE
possible issue: clicking dots twice refreshes screen

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#591]
clicking on an icon resets screen rather than zooming in - i had issues setting up my environment when i noticed it so it may or may not exist

to recreate:

1) zoom out to find a nearby icon (i was away from london so mine weren't visible)

2) click on it

- map zooms in on it -

3) click on it again. 

- maps resets.

expected behaviour - map zooms in closer on the icon

related:

clicking the blue arrow on a list item zooms to the activity if it's on screen

if its off screen the map also resets unexpectedly

expected behaviour - zoom and center on the resource/activity clicked on

**Comment by royGil** [comment]
fixed
