### ISSUE TITLE
improve appearance of 'time' from 00:01:00 - 1pm or 13:00

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#6]

**Comment by mordka** [comment]
@patison89 this is something for you, here we have a method which is populating the dropdown, in the new event form https://github.com/mordka/fl-events/blob/master/both/collections/events.js#L220-L229
We need to currently it's outputting an array e.g. ['00:00','00:30'] and so on. We need to amend it to result in more readable format. And we can skip some late night hours.
So let's say from 08:00 am till 12:00pm ? with 30 minute intervals?

**Comment by AndyatFocallocal** [comment]
![dialogue box](https://cloud.githubusercontent.com/assets/16229696/17344735/2de6e2cc-58fb-11e6-8c8f-d430f141b09f.png)

![text edit](https://cloud.githubusercontent.com/assets/16229696/17344747/36cd7284-58fb-11e6-8862-6d0a44c1e95c.png)

**Comment by ydaniel98** [comment]
@AndyatFocallocal This issue seems to have been already fixed for the most part. I created a PR (#68) with @mordka 's suggestion of setting the start time to 8:00 and fixed the time format for the event detail view.

**Comment by AndyatFocallocal** [comment]
great effort @ydaniel98 :0)

**Comment by ydaniel98** [comment]
I will close this issue since issue #20 is already time related.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 which solution did we go with to resolve the issue?

does it pull the timezone from a user? and if so can we check gathering/resource creation from different time zones using a proxy to see if people travelling will find the times appearing in their home time-zone rather than the actual time set? as happens now on facebook?

or did we go with just showing the time selected by the user, and ignoring timezones entirely (which would be my prefered method as it is bullet/bug-proof)

**Comment by ydaniel98** [comment]
@AndyatFocallocal I was thinking that we could display time in two different time zones. One with the event time zone and another with the user time zone. That could avoid the travelling confusion. (issue #20). How does that sound?

**Comment by AndyatFocallocal** [comment]
@ydaniel98 we could do that.

i'm just a fan of super simplicity. if the user sets the time at 3pm and its in France, i don't see the need for the system to know, or consider my timezone. if it lists it as 15:00 no-one can get confused. 

consider if a user is in the UK and flying to France. they want to meet people in France, so create a gathering. there is an extra layer which they could get confused by, when they review their gathering, if the system is listing the activity in two time zones. 

if i were in the UK and creating a gathering in france, it is obvious to me the user, that i should use the French time zone, and that the time listed on the gathering in France, is the time the gathering will commence in France - and to everyone who views it.

why add anything which adds potential complication?

**Comment by ydaniel98** [comment]
@AndyatFocallocal Good point. I'll remove the time zones all together then, after finishing up issue #69.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 awesome :)
