### ISSUE TITLE
change background colour to #FFF9EB

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#658]
on the homepage and about page. its a warmer colour, much more welcoming than the current grey

![image](https://user-images.githubusercontent.com/16229696/42340508-1febf0e8-8088-11e8-8a95-bb56f9b8086c.png)

**Comment by endurain** [comment]
I hope this is the best place to put this. Just trying to figure out what you're looking for and understand the project better. Just #FFF9EB for the entire background? Or adding additional tones (#FFE8B3) to give any depth? 

![screenshot from 2018-07-10 13-21-38](https://user-images.githubusercontent.com/37851511/42532498-4e176a82-8444-11e8-9116-e4f6aec2eec1.png)

**Comment by AndyatFocallocal** [comment]
It's best to use slack for communication as we get push notifications. The
darker yellow looks too much, I'd just stick with the one tone and light
yellow background

**Comment by NathanScott85** [comment]
Issue Resolved using #FFF9EB, pull request sent
