### ISSUE TITLE
Detective work: Focallocal.org is blocked on some ISP's. Brightertomorrowmap.com is not. Whats causing it?

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#673]
Focallocal.org and all its subdomains are being blocked on some ISP's, yet Brightertomorrowmap.com with the same code base is not being blocked. 

I suspect this is an issue with our domain setup, or our SSL setup. If you'd like to look into this message Andy for more details and access tot he required servers and services. 

Trying to connect on BT in the UK.
![image](https://user-images.githubusercontent.com/16229696/43854831-e83d146e-9b3b-11e8-979b-8d2fe2b80d45.png)

From Aline in South America
![image](https://user-images.githubusercontent.com/16229696/43855134-a481d7cc-9b3c-11e8-88a7-3f283b65ca40.png)

![image](https://user-images.githubusercontent.com/16229696/43855165-b1118f14-9b3c-11e8-94d0-15661b127043.png)

**Comment by nsrtky** [comment]
Checkout domain name registretor dns settings and vultr dns  may dns servers changed?
we ensure dns server of ,thatis is something like vultr ns1.vultr.com, is added at dns settings of domain name reistrator dns setting?

**Comment by AndyatFocallocal** [comment]
Thanks Kaya. @ydaniel98 worked hard on it, it seems there is something not right with it though. If you wanted to have a look at them i'd be happy to give you access
