### ISSUE TITLE
after making an action buttons cease working

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#69]
i've noticed this before, the situation i'm noticing it in now is:

load the site. 

click icon

click show more

page loads fine

return to map

click icon

click show more - nothing happens

i can't remember the situation when this happened last, but i'm also noticing that you can't click anything on the map, and the dots aren't combining after creating a new dot - until you manually refresh the window.

i have a strong suspicion that if we make the page auto-refresh/reload after completing an action, all of these bugs will be resolved.

**Comment by ydaniel98** [comment]
@AndyatFocallocal  Reloading the page after creating an event will render the feature of panning to the newly created event unnecessary. However this can be done after returning to the map from the calendar, home or the show more view.

**Comment by AndyatFocallocal** [comment]
@ydaniel98  sounds fine to me, as long as it solves that inability to click on anything on the map. great effort by the way
