### ISSUE TITLE
Review all changes to branch 'master' to see if they were pushed to fl-sleeper.

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#701]
Changes used to be pushed to both maps automatically. after that function broke many changes have been made on the master branch and not pushed to fl-sleeper. 

the code will diverge after the hack using a cherry pick method. until today, most changes should have been pushed to both maps.

**Comment by DnMcky** [comment]
How do we close the issue? @AndyatFocallocal

**Comment by AndyatFocallocal** [comment]
legend!
