### ISSUE TITLE
Both: Intregration of discussions

### ISSUE THREAD

**Issue by sylque** [focallocal/fl-maps#705]
The plan is to have Discourse discussions (discuss.focallocal.org) directly available within the application.

When on a BTM page like [this one](https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP) (guess what, such a page is called a "Page" in the application :-), you could click on some links/buttons/whatever and have related discussions displayed on the right.

Here is an example of what we want to achieve (on a third-party web site, not related to Focallocal): http://dcs.link/kzdf8p. To see it in action, click an orange balloon.

**Comment by sylque** [comment]
Here is a fork to work on this: https://github.com/sylque/fl-maps
As a first step, I implemented a very basic UI to display the Focallocal forum on the right.

**Comment by OlivierJM** [comment]
I have checked the link it looks great, so I guess as you have mentioned we need to add those buttons to take to the discourse from anywhere.

**Comment by sylque** [comment]
Here is how I see this: 
1- one or more React devs should take it from here and be responsible for the UI part
2- i will focus on the "backend" part (communication between the UI and Discourse)

On the UI part, what needs to be done is:
- Cleanup my dirty React code
- Redesign the Page component to have the Discourse interaction (more on this below)

**Comment by OlivierJM** [comment]
I can take the react part, It would be good if there is one more for the designs or to do the clean up.

**Comment by sylque** [comment]
Regarding the Page component (like [this one](https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP)), here is a rough idea from Andy:

<img src="https://user-images.githubusercontent.com/42490951/47253722-84335500-d457-11e8-92bf-710fb3f00764.png" width="200">

He said: _"i think the top two should be above 'about' and the bottom two just above the map"_


Then I implemented this:

<img src="https://user-images.githubusercontent.com/42490951/47253771-4b47b000-d458-11e8-945a-574c9dbe9c7c.png" width="600">

But he said he got used to the balloons and he would love to have them back.

That's the state of the design right now. I think it needs some more thoughts.

**Comment by AndyatFocallocal** [comment]
i think balloons are better than blue links, as they stand out from ordinary site links so once a user becomes familiar with our site they will quickly know what that means, where with a blue link it will always be a guess if it is opening the forum or taking the user to an external site

**Comment by AndyatFocallocal** [comment]
i'm happy to help with designs. i've been working with the UX/UI guys on our site and think i'm fairly competent now (with the occasional habit of making things too complicated)

@OlivierJM is this ok to merge now?

**Comment by OlivierJM** [comment]
I have cloned @sylque's fork, I am going to take and see what can be improved and how those ballons can be added. 
Thanks

**Comment by sylque** [comment]
Also, on the React side, we need to integrate the feature with the router. 

Suppose a user opens the right panel, then copies the url from the address bar and send it to a friend. When the friend opens the link, we want to restore the same page state, i.e. with the right panel opened.

The state of the right panel is described like this:
1. Is the right panel opened or closed?
2. Does it contain a topic list corresponding to an orange balloon? If it does, which Discourse tag?
3. Does it contain a topic corresponding to an orange balloon? If it does, which topic id?
4. Does it contain another Discourse page? If it does, which page?

In the past, what I did is to add 4 search params in URLs. Suppose we call them `dcsr`, `dcsl`, `dcst`, `dcsd`. The result are urls of the form:
```
// Right panel opened
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcsr=1&dcsl=wall
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcsr=1&dcst=383
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcsr=1&dcsd=%2Fu%2Fsyl%2Fmessages

// Same with right panel closed
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcsl=wall
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcst=383
https://brightertomorrowmap.com/page/wsbM4AKFywAJDhySP?dcsd=%2Fu%2Fsyl%2Fmessages
```

Any thoughts about this? Anyone familiar with the React Router?

**Comment by OlivierJM** [comment]
Heyy @sylque you can commit the changes, I will try and see if I can maintain the state in the router if not I will ask help from @ydaniel98 .

**Comment by sylque** [comment]
Ok. Need 30 minutes.

**Comment by OlivierJM** [comment]
Alright, I am heading out to look for a better internet, I should be there in less than 30 minutes, don't worry about how dirty it is, I will do my best to clean things up.

**Comment by OlivierJM** [comment]
Heyy @sylque can you create a pull request so that I see the changes, I checked your fork, I can't access them but am able to see them here on github.

**Comment by OlivierJM** [comment]
I think I have gotten it, I had not checked out the docuss branch.

**Comment by sylque** [comment]
Things remaining to be done:

1. Moving Olivier's code to the App so that search params are managed at the App level (whatever the page).
2. Adding a selection indicator to ‘Photos’, ‘Videos’, etc. so that we can see which one is selected.
3. Completing the onDiscourseRouteChange hook. There is a little trick there I will need to explain.  It will require requesting some Meteor collections.
4. Checking with Andy about the UI and making final adjustments.

**Comment by DnMcky** [comment]
are there to be selection indicators on every page?

**Comment by DnMcky** [comment]
@sylque whats the best way for me to get the work I have done into your forks branch?

I had cloned your fork and was working in the branch, just realised I cant push to it though

**Comment by sylque** [comment]
Integration of discussions is done. For additional feature requests and bug reports, please create new Github issues.
