### ISSUE TITLE
Home Page: Auth issue

### ISSUE THREAD

**Issue by badpointer** [focallocal/fl-maps#731]
Looking at the home page I noticed that being logged in won't show how to help section.
Looks like the Component HowToHelpSection isn't being passed some Auth property to toggle.
**This is the Warning/Error: this property isn't being passed down from Home Page**
<img width="882" alt="screen shot 2018-10-20 at 11 20 04 pm" src="https://user-images.githubusercontent.com/6944604/47263067-40743600-d4bf-11e8-9d47-e536e89ede72.png">

Here is property and how it toggles:
<img width="1137" alt="screen shot 2018-10-20 at 11 21 20 pm" src="https://user-images.githubusercontent.com/6944604/47263074-71ed0180-d4bf-11e8-9d0a-ba2a88ca436b.png">

This is the Home component and we can see the HowToHelpSection isn't being passed an auth or boolean property.
<img width="437" alt="screen shot 2018-10-20 at 11 21 33 pm" src="https://user-images.githubusercontent.com/6944604/47263078-91842a00-d4bf-11e8-8e5e-e1752be7d5b7.png">

**Comment by AndyatFocallocal** [comment]
I'm currently unable to login (fl-master). Is this the likely culprit?

I last logged in on focallocal.org yesterday morning and stayed logged in

We use discourse as an SEO client, so users can remain logged in across our site. This would be where I'd suggest starting looking
