### ISSUE TITLE
The Page component doesn't handle route change

### ISSUE THREAD

**Issue by sylque** [focallocal/fl-maps#742]
The Discourse integration code needs to issue route changes in fl-maps. The reason is that, in Discourse, when the user opens a topic associated with a Page, then the fl-maps route needs to be changed to this Page.

The issue reported here occurs when the user is currently viewing a Page. When Discourse triggers a route change to a Page with a different Event id, the URL is changed but the Page is not refreshed. In other words, if you are on `https://brightertomorrowmap.com/page/aaaaa` and Discourse issues this JS command: `history.push({ pathname: '/bbbbb' })`, then nothing happens on the screen, except for the URL change in the address bar.

I've made a small test: if, in a Page, you insert a link to another Page, then the link works as expected (i.e. the page is refreshed when clicking the link). That is surprising to me, as the Page code doesn't seem to handle refresh at all. So maybe I'm missing something.

Do I do something wrong? Or is the Page code needs to be worked on?

**Comment by badpointer** [comment]
I assume it's because you are not telling react router to redirect to that page. Calling the **path.history.push()** will push an entry to the history stack.
Try swapping **push** with **replace()** which replaces the current history on the stack.

If both options don't work try using <Redirect /> component.

**Comment by badpointer** [comment]
Docs: [React Router History](https://reacttraining.com/react-router/web/api/history)
You might also want to use Location than history because of mutation issues.

**Comment by sylque** [comment]
Thanks, @badpointer.
* `push` and `replace` both show the issue.
* If, by *use Location*, you mean changing the route with `location.href=...`, I think that's an excellent workaround and I will implement it right now! However, the UX will be terrible, as both fl-maps and Discourse will reload when the user clicks a topic. It might also mess up with the browser history, causing issues when users click the "back" button. So it can only be a temporary fix. 
* I'm not quite sure what you mean by "using component".

I can now confirm the issue lies in how the Page component is implemented:
* The reason why, earlier, I was confused, is because I didn't insert the html link the React way. I used a standard "a" tag, which reloads the app entirely. So it didn't prove anything.
* However, if, in a Page you insert a link the React way (`<Link to={'/page/M7TNaCTahN4fFsKtF'}>Another page</Link>`), it doesn't work. The link changes the address bar, but doesn't refresh the page, proving something is wrong in the Page component.
* This seems to be a common issue with React: see [this](https://stackoverflow.com/a/43083937/3567351), for example.
