### ISSUE TITLE
Any url redirects to the home page

### ISSUE THREAD

**Issue by sylque** [focallocal/fl-maps#773]
If I email an url to my friend (such as `https://focallocal.org/page/p7cEkH8MmBDnLF5Qp`) and he clicks on the link, he is redirected to the home page (`https://focallocal.org/home`) and cannot see the page I wanted him to see.

This issue has appeared in `new-master` and is due to this line: 
https://github.com/focallocal/fl-maps/blob/master/imports/client/ui/app.js#L63

**Comment by AndyatFocallocal** [comment]
@kevin-06-huang has already begun work on this. your note here might help him find the cause, Kevin is the due to the 404 redirect hack

**Comment by AgentBoo** [comment]
I commented out that line in my pull request #772. I was fixing the modal and that line made the modal always redirect to /home.

**Comment by AgentBoo** [comment]
It's in both.

**Comment by sylque** [comment]
Looks ok now.
