### ISSUE TITLE
Both, urgent: a URL in text on a page breaks the CSS

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#786]
If a user adds a long URL in the text it breaks the page so half the text appears outside the visible window.

This one: http://www.decentralizeddanceparty.com/the-party-manifesto/

Suggested solution: add a URL box where multiple links can be added in the new page creation form, which turns the string into an icon after the users chosen text. For example:

'DDP How to Party Manual' (link)

Also the text entry boxes (description, etc) should reject urls

**Comment by timothyjchase** [comment]
@AndyatFocallocal I tried to recreate this one by adding a resource with URLs:

### Resource with URLs
<img width="546" alt="screen0" src="https://user-images.githubusercontent.com/36645667/48110966-31121e00-e21d-11e8-8c4a-f517674d70c1.png">

### Resource in search results
<img width="500" alt="screen1" src="https://user-images.githubusercontent.com/36645667/48110969-34a5a500-e21d-11e8-9a08-e928087904d6.png">

### Resource expanded
<img width="484" alt="screen2" src="https://user-images.githubusercontent.com/36645667/48110974-38d1c280-e21d-11e8-87a5-f41bb35a5c7d.png">

### Resource page
<img width="1052" alt="screen3" src="https://user-images.githubusercontent.com/36645667/48110982-3c654980-e21d-11e8-95a5-027f3f37a434.png">

Can you please clarify how to recreate the issue? Thanks.

**Comment by artysidorenko** [comment]
looking into this

**Comment by AndyatFocallocal** [comment]
Cool. It only seems to happen when it's a long URL. It would look better with an auto link shortener anyway
