### ISSUE TITLE
both, key task: investigate why the maps won't load on Opera browser and fix

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#797]
Users of Opera browser on desktop and mobile appear to be just seeing a blank screen when loading focallocal.org or brightertomorrowmap.com. 

Please investigate and find a fix for this. there is a chance this is related to our lack of a 404 page, which is causing our site to be blacklisted on some security lists

**Comment by vermiculite** [comment]
@AndyatFocallocal I have just looked at opera desktop and both sites load maps correctly. I think the issue is not opera. I was unable to install opera on my phone.

**Comment by AndyatFocallocal** [comment]
@vermiculite I had a suspicion that this only occurs on old browsers. Probably best to leave it unless a lot of users are having troubles as backwards compatibility can be an endless loop. Or we could have an error message show advising users to update their browsers

**Comment by AndyatFocallocal** [comment]
Thanks for checking
