### ISSUE TITLE
Focallocal.org only: please change menu logo for the one used in action.focallocal.org

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#799]
the logo in the main menu at focallocal.org should be the same as the one here:

![image](https://user-images.githubusercontent.com/16229696/48431553-e555fc00-e769-11e8-8a90-ca07cde68e46.png)

**Comment by h4xhor** [comment]
Hi @AndyatFocallocal, so just to confirm you want the current tree picture logo at https://focallocal.org/ to be replaced with this 100% word logo as shown at https://action.focallocal.org/ ?
![focallocallogoqs](https://user-images.githubusercontent.com/14309370/51796437-8e6ea780-222d-11e9-9f00-12d98730d165.png)
Best regards,
h4xhor

**Comment by AndyatFocallocal** [comment]
Yes please 🙂
