### ISSUE TITLE
Better integration of the suggested activities list and the map?

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#80]
currently the suggested activities are in their own section and on the Megamenu. they feel very isolated over there and very few users actually visit them.

http://news.focallocal.org/activities-list/

as a user i'd like them to be more integrated into map so i can easily read and watch videos about the suggested activities. how can we achieve that?

**Comment by jonscv** [comment]
Hi guys,
Just to get some ideas flowing and to make things a bit more visual, I made a quick sketch of how I envisage Andy's suggestion...please see attachment. 

(1) In the attachment, you will see a menu containing radio buttons to select desired activities. "Show button", will then populate a map with selected point of interest.
(2) Click on point of interest and popup window with event details and link to view video appears.
![2017-02-02 16 51 50](https://cloud.githubusercontent.com/assets/11708285/22559592/7ee6c51c-e969-11e6-9fb1-34e0fa2d2ca4.png)
