### ISSUE TITLE
Both: Feature - Topic count badges

### ISSUE THREAD

**Issue by sylque** [focallocal/fl-maps#821]
This feature request is an addition to feature https://github.com/focallocal/fl-maps/issues/705.

When integrating discussions in fl-maps, one feature has been forgotten: **topic count badges**. They can be seen in [this demo](http://dcs.link/kzdf8p) (the number in a circle at the right of "Foundation Board of Directors").

**Comment by AndyatFocallocal** [comment]
just want to keep track of this.

**Comment by sylque** [comment]
Just created the PR for this (fl-maps only). Please let me know if it works for you.

**Comment by TLMcNulty** [comment]
LGTM
