### ISSUE TITLE
Both: Users posting a resource are automatically subscribed ('following') the Discourse topics on their page

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#822]
I found a way to do this a while back for our wordpress articles, but then found an alternative solution. It looks like it should work in our maps/docus integration

https://meta.discourse.org/t/how-to-create-a-follow-button-for-a-topic-and-post-it-on-an-external-website/91266/2

@sylque this is probably your area of expertise

**Comment by sylque** [comment]
I'm also tracking this issue here: https://github.com/sylque/dcs-discourse-plugin/issues/8.
