### ISSUE TITLE
Not Mobile friendly

### ISSUE THREAD

**Issue by iamlasse** [focallocal/fl-maps#83]
Are there plans to create a more mobile friendly version. I browsed on an iPhone 5s and it was very hard to navigate. Hamburger menu didn't work at all.

**Comment by iamlasse** [comment]
#bug

**Comment by AndyatFocallocal** [comment]
we haven't got anything specific planned as yet, although you'd be welcome to make suggestions.

i'm glad you took the time to comment, the hamburger menu was previously working and i wasn't aware it had broken. i'll create an issue 

we also have plans to improve the filters window asap. hopefully during this weekends Homelessness Hack, as that is clearly not enjoyable to use. and update the 'Add Gather/Add Resource' window into a chain of single/double entry fields which should improve user experience.

Is there anything else you noticed? @iamlasse

**Comment by iamlasse** [comment]
I'll have a look.

**Comment by AndyatFocallocal** [comment]
great. 

the UX/UI team had a look last week and made a few other suggestions which should be fairly easy to implement. i'll add them into the 1.5 milestone today
