### ISSUE TITLE
Bug: Hamburger menu not opening on mobile

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#84]
It appears the hamburger menu has broken when used on small screen devices. Tested on Iphone5 and Oppo Find 7a, android and IOS.

**Comment by Angamanga** [comment]
@AndyatFocallocal Which hamburger-menu? The one on the map opening the different layers or the menu-bar-hamburger? I get the menu-bar-hamburger to open but not the map-hamburger.

**Comment by AndyatFocallocal** [comment]
@Angamanga yup the map-hamburger

**Comment by ydaniel98** [comment]
@AndyatFocallocal @Angamanga When implementing google maps I had to recode the legend. This should now be fixed.

**Comment by AndyatFocallocal** [comment]
Awesome! It solved so many issues

**Comment by AndyatFocallocal** [comment]
i found this issue again when i resized my screen to tablet size. clicking the hamburger menu to the left of the top menu (where top menu items have hidden) makes the screen go dark, but the icons are not visible

**Comment by AndyatFocallocal** [comment]
![image](https://cloud.githubusercontent.com/assets/16229696/23384260/6453b24c-fd4a-11e6-93fc-82b988c79c64.png)

**Comment by AndyatFocallocal** [comment]
please ignore the insane amount of things on my desktop. i have a google drive issue which i need to resolve and begun storing things there temporarily, and.... well, yeah. :P

**Comment by AndyatFocallocal** [comment]
update: the menu is being rebuilt by @ydaniel98 @Spartano 

left side (navigation):

order left to right
1) About Us
http://focallocal.org

drop downs:
1.1.) hire us
(to be created)
http://hire.focallocal.org
1.2) community values
http://news.focallocal.org/the-focallocal-community-values/
1.3.) F.A.Q
(to be created)
http://news.focallocal.org/faqs
1.4.) the road to Focallocal
http://news.focallocal.org/about-andy-and-the-road-to-focallocal/
1.5.) will we succeed?
http://news.focallocal.org/are-we-sure-of-success/
1.6.) Focallocal in the news
http://news.focallocal.org/category/in-the-news/

2) Happy News
http://news.focallocal.org

3) Action Center
http://action.focallocal.org/

4) Shop
1) Positive Action Shop 
(to be rebuilt within the next week)
https://the-positive-action-shop.myshopify.com/
2) Community Marketplace 
(coming in May)
http://shop.focallocal.org/

5) Gather
http://gather.focallocal.org/

6) Projects
6.1) Positive Action Ideas
(to be created. estimated 2 weeks)
http://activities.focallocal.org
6.2) Brighter Tomorrows map
http://brightertomorrowmap.com/

[2:01]  
Right Menu (actions)
order right to left
note: this menu changes on every section to show the actions available to users, and does not ever minimise

1) Home
2) Map
3) List
4) Profile [icon/avatar only] (edited)

If the new menu you are creating can be used anywhere on the website, and i can just update the right links for each section, that would actually be the best solution as it means the navigation would remain identical on every page - and fix the broken minify function on action.focallocal.org, and the icons on news.focallocal.org. which have been on my to-do list for far too long.

i'm not sure how specific the new menu is to meteor, or whether dropping it into headers anywhere would be a possibility. if not i'll need to find a similar drop down element for the left menu and try to match it
