### ISSUE TITLE
cascading windows entry form. small bug

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#86]
when filling out the form it shouldn't allow the user to advance to the next window when an entry box is incomplete.

(good work though :+1: )

**Comment by ydaniel98** [comment]
@AndyatFocallocal That's what I mentioned in the pull request. I have not yet implemented validation.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 ah, ok awesome effort then

needs a little design change (smaller windows), and a few edits to the text/options. but this is a big step forwards!

**Comment by ydaniel98** [comment]
@AndyatFocallocal This has been fixed. PR #87
