### ISSUE TITLE
Bug: Repeating events don't say when they are repeating  (time date modal)

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#867]
The event set to repeat every two weeks needs to say when the next repeating event will be. It just says 'every two weeks', not which week it will be.

![image](https://user-images.githubusercontent.com/16229696/52419535-3581f780-2ae8-11e9-91cf-153e281d77a2.png)

**Comment by artysidorenko** [comment]
Hey @AndyatFocallocal  - looks like this is working better now. (Tom sent me the db entry: event starting date was on week of the 11th Feb, so next event from today is correctly displaying as 11th March).

I'll close this issue for now unless you have any Qs.

![screenshot from 2019-03-01 16-30-05](https://user-images.githubusercontent.com/26905074/53652527-040ccf80-3c41-11e9-974c-993fbde9705e.png)

**Comment by artysidorenko** [comment]
yikes sorry for the blow up screenshot

**Comment by AndyatFocallocal** [comment]
yes, this looks brilliant now!
