### ISSUE TITLE
Bug: user can post event recurring every week, ignoring day of the week field. Subsequent event page causes crash

### ISSUE THREAD

**Issue by artysidorenko** [focallocal/fl-maps#879]
Currently users are able to create an event, repeating weekly, and leave the choice of weekday field blank(see pic 1).
This creates an invalid event in the database, and subsequent requests to the event page cause a crash due to the missing data field (pic 2).

Pic 1:
![screenshot from 2019-02-16 23-00-42](https://user-images.githubusercontent.com/26905074/52906247-cde24f80-323f-11e9-84af-976a85701711.png)

Pic 2:
![screenshot from 2019-02-16 23-03-26](https://user-images.githubusercontent.com/26905074/52906269-2dd8f600-3240-11e9-9e6d-bdf92b3bd297.png)

**Comment by AndyatFocallocal** [comment]
Good spot, I'll add it to Trello 🙂

**Comment by AndyatFocallocal** [comment]
@artysidorenko this must be what broke the page in Groningen. Great find, it's stopped me from using the platform here. do you think this change will fix previous events created which are broken?

**Comment by artysidorenko** [comment]
@AndyatFocallocal not familiar with the issue in Groningen, if it helps confirm if it's this: this particular bug would cause a crash when you actually click to expand the event; the map and list still work up until the point you click.

My change only works on new events at the moment I'm afraid, but if you come across any old events that crash like I describe above let me know and I'll take a look at them specifically, if I can sort something retroactively. I hadn't found any events using the "repeat weekly" functionality myself so was hoping it hadn't been encountered by other users yet (I only came across this while typing up some test cases for another mission I was working on).

**Comment by AndyatFocallocal** [comment]
@artysidorenko , thats the exact behaviour it is exhibiting. i've asked @TLMcNulty to try and delete it in via the database. it's great to know that you've identified that issue and fixed it so it won't happen again

**Comment by AndyatFocallocal** [comment]
and only encountered by me unfortunately/fortunately
