### ISSUE TITLE
Add search bar to map so users can zoom in to their location, town, street, etc

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#88]

**Comment by ydaniel98** [comment]
@AndyatFocallocal Thankfully, much of the code for this is already done. It would be pretty much the same as the address input in the new event form.

**Comment by ydaniel98** [comment]
@AndyatFocallocal If google maps is implemented, It probably already includes a search bar.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 can you contact David as he's working on it right now and you guys can chat

**Comment by ydaniel98** [comment]
@AndyatFocallocal What's his username? Also, should I contact him through the form?

**Comment by AndyatFocallocal** [comment]
@eldavimost @ydaniel98  ..go :0)

**Comment by AndyatFocallocal** [comment]
you guys should should have a quick 10/15min chat to make sure you are on the same page. not much till launch, working together, maybe it could be finished today?!!?! :dancing_men: 


click here and you're in a video meeting: https://zoom.us/j/250694428

**Comment by ydaniel98** [comment]
Hello, @eldavimost. How is google maps going to be implemented and does the api already include a search bar?

**Comment by AndyatFocallocal** [comment]
hey, david is in the video meeting. click the link and say hi :)

**Comment by ydaniel98** [comment]
@eldavimost This is my email.
ed22333t@gmail.com

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'll get started implementing google maps in the project. I'll create a separate issue for it.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 in a rush, sorry dude. didn't have time to search for the new issue. can i request this map in the implementation please: https://snazzymaps.com/style/34/neon-world

**Comment by AndyatFocallocal** [comment]
@ydaniel98 if its more than 2min job don't worry, but if its simply editing a colour code can i request that we tone down the red on that neon map when its fully zoomed in to a slightly lighter and more orange shade. 
really not a big issue, we can easily do that later too

**Comment by ydaniel98** [comment]
@AndyatFocallocal From the url you provided it looks pretty easy. I'll give it a go.

**Comment by AndyatFocallocal** [comment]
@ydaniel98 i don't see the search bar. also we're going to need to move the + Add symbol as its now conflicting with the +/- keys on Google Map

**Comment by ydaniel98** [comment]
@AndyatFocallocal I'm not yet done with this issue. There is a little bit more work to be done.
