### ISSUE TITLE
search for http in codebase and change to a https source.

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#903]
Perform codebase wide search for ‘http://’ to locate where the insecure images are being loaded from, and change to a https source, hopefully from the same source

**Comment by kristophesankar** [comment]
This might be tricky...I can do a regex to search the entire codebase but how do we cater for the instances where there are no secure links?

**Comment by AndyatFocallocal** [comment]
If they don't exist we can either leave them. Or download them, post them on Imgur, and call them from there.

I fixed three images last week like this so hopefully there's not too many left. I specifically don't have the code on my local machine though as it pulls me into coding and away from supporting and growing the commununity, so I wasn't able to perform a codebase wide search

**Comment by kristophesankar** [comment]
I performed a code wide search and it produces a large list of files. Are these issues specific to the front end code or back-end also? Might help me narrow down the images. I used the regex expression found here: https://regexr.com/3g1v7 in sublime to get the list.

**Comment by AndyatFocallocal** [comment]
@kristophesankar good work. can you please post your results into the meteor-maps thread in slack so we can all discuss them :+1:

**Comment by kristophesankar** [comment]
Will do!
