### ISSUE TITLE
Update Map to Neon version

### ISSUE THREAD

**Issue by AndyatFocallocal** [focallocal/fl-maps#95]
https://snazzymaps.com/style/34/neon-world

and change the red tone on the nearest view to a lighter blue colour (or any more relaxed colour than the aggressive red)

**Comment by AndyatFocallocal** [comment]
@Spartano has this issue been resolved? i can't see any changes on the map

**Comment by Spartano** [comment]
In the pull request you should see the changes in the code. You can copy
paste any map you like now.

Il 14 Feb 2017 4:39 PM, "AndyatFocallocal" <notifications@github.com> ha
scritto:
